### ISSUE TITLE
无语

### ISSUE THREAD

**Issue by zhutingfa** [dianping/puma#46]
你们这个项目很多依赖公司内部的jar
根本就没发运行啊
能否把贵公司的maven私服公开一下啊

**Comment by ainilife** [comment]
近期有调整重新开源，敬请期待。

**Comment by yunfan123** [comment]
+1，既然开源了，一些依赖的组件都不提供。

**Comment by zhutingfa** [comment]
用阿里的otter挺好的
https://github.com/alibaba/otter

在 2016-11-16 11:53:02，"yunfan123" notifications@github.com 写道：

+1，既然开源了，一些依赖的组件都不提供。
